# Generated by Django 5.0.6 on 2024-05-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Oila', 'verbose_name_plural': 'Oilalar'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Odam', 'verbose_name_plural': 'Odamlar'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': "Ro'yxat", 'verbose_name_plural': "Ro'yxatlar"},
        ),
    ]
